server:
  port: 8800

spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  #JPA : https://seungh1024.tistory.com/52
  jpa:
    hibernate:
      # 엔티티를 기준으로 테이블을 생성하는 규칙을 정의.
      ddl-auto: update  # update: 엔티티의 변경된 부분만 적용.
    properties:
      hibernate:
        format_sql: true      # 모든 쿼리문을 콘솔에 출력하는 설정 default는 false.
        show_sql: true        # 콘솔, 로그의 sql을 예쁘게 출력.
        highlight-sql: true   # ANSI secape codes를 사용하여 가독성을 높여줌.
        dialect: org.hibernate.dialect.MySQLDialect
    # db 시작전 기본으로 넣어주고 싶은 값들을 data.sql 파일을 작성하여 적용하기 위한 설정.
    defer-datasource-initialization: true